### PR TITLE
enh(drawio): allow style edit on whole selection

### PR DESCRIPTION
**Pull request by Yassir-BenBOUBKER**
add a selector for Resources Style
image

### CODE REVIEW

**Comment by bdauria** [comment]
@Yassir-BenBOUBKER we need to ve VERY CAREFUL about mixing map logic into Draw.io, i would prefer to stay in the react world as much as we can (for obvious maintenance reasons)

**Comment by Yassir-BenBOUBKER** [comment]
> @Yassir-BenBOUBKER we need to ve VERY CAREFUL about mixing map logic into Draw.io, i would prefer to stay in the react world as much as we can (for obvious maintenance reasons)

yes, but these are style attributes that don't need error handling, so I thought it would be better to do this in drawio

**Comment by Thebarda** [comment]
> yes, but these are style attributes that don't need error handling, so I thought it would be better to do this in drawio

Is it possible to move the fix into a React environment ?

**Comment by Yassir-BenBOUBKER** [comment]
> > yes, but these are style attributes that don't need error handling, so I thought it would be better to do this in drawio
> 
> Is it possible to move the fix into a React environment ?

it alrady existe in editData modal but for just one shape
the task is to enable style change for multiple shape at the same time

**Comment by Yassir-BenBOUBKER** [comment]
> > > yes, but these are style attributes that don't need error handling, so I thought it would be better to do this in drawio
> > 
> > 
> > Is it possible to move the fix into a React environment ?
> 
> it alrady existe in editData modal but for just one shape the task is to enable style change for multiple shape at the same time
@Thebarda @bdauria

**Comment by bdauria** [comment]
@Yassir-BenBOUBKER we might want to add a contextual menu when multiple items are selected and do it there (that'd be in React)

**Comment by Yassir-BenBOUBKER** [comment]
Closed: because it need to be done using React
waiting for migration to monorepo

**Pull request closed without merging**
